### ISSUE TITLE
KeyError: 'Size'

### ISSUE THREAD

**Issue by zidanmahmoud** [avibrazil/iOSbackup#17]
I am trying to extract data from an encrypted backup of an iPhone7 iOS 13.2.3

I ran all the code in `README.md` fine up to the media extraction point:
```python
backup.getFolderDecryptedCopy(
	'Media',
	targetFolder='./restored-photos',
	includeDomains='CameraRollDomain',
	excludeFiles='%.MOV'
)
```
where I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    backup.getFolderDecryptedCopy(
  File "/home/mahmud/.local/lib/python3.8/site-packages/iOSbackup/__init__.py", line 671, in getFolderDecryptedCopy
    info=self.getFileDecryptedCopy(
  File "/home/mahmud/.local/lib/python3.8/site-packages/iOSbackup/__init__.py", line 944, in getFileDecryptedCopy
    info=iOSbackup.getFileInfo(manifestEntry['manifest'])
  File "/home/mahmud/.local/lib/python3.8/site-packages/iOSbackup/__init__.py", line 783, in getFileInfo
    "size": fileData['Size'],
KeyError: 'Size'
```

I have tried running it with `cleartextpassword` as well as `derivedkey`
```python
backup = iOSbackup(
    udid="86536f75e0143010a3281631c86ac9b6d81473c8",
    cleartextpassword="secret :p",
    # derivedkey="secret :p",
    backuproot="~/Documents/BACKUP_IOS/"
)
```

**Comment by avibrazil** [comment]
This was fixed in latest version 0.9.923
