### ISSUE TITLE
sqlite3.DatabaseError: file is not a database

### ISSUE THREAD

**Issue by soundsk** [avibrazil/iOSbackup#25]
Hi!

Trying to use this to decrypt and recover files from an old iPhone backup but keep getting this error, any idea what's wrong?
Thanks!

`>>> b=iOSbackup(
...     udid="64004deb35e37f1ce7e698bd4b9a1926aae37d59",
...     cleartextpassword="supersecretpassword",
...     backuproot='Backup'
... )
>>> 
>>> 
>>> b.getFolderDecryptedCopy(
...     includeDomains='CameraRollDomain',
...     targetFolder='restored-photos',
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/iOSbackup/__init__.py", line 654, in getFolderDecryptedCopy
    backupFiles = catalog.cursor().execute(query).fetchall()
sqlite3.DatabaseError: file is not a database
>>> `

**Comment by natarajan0007** [comment]
It might be due the problem with the backuproot = "Backup" path. Try to provide explicit path where the encrypted backup file exist.
