### ISSUE TITLE
I get a StopIteration when running getDeviceList()

### ISSUE THREAD

**Issue by ddofborg** [avibrazil/iOSbackup#27]
I get a `StopIteration` when running `getDeviceList()`. I am on MacOS Ventura. Any ideas?

    >>> from iOSbackup import iOSbackup
    >>> iOSbackup.getDeviceList()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/iphone_backup_extract/venv/lib/python3.8/site-packages/iOSbackup/__init__.py", line 374, in getDeviceList
        (_, dirnames, _)=next(os.walk(root))
    StopIteration

**Comment by Andre81** [comment]
I have the same problem with OSX Ventura 13.1.
You can resolve by setting permission to access the whole disk to terminal app
