### ISSUE TITLE
Use on windows 8.1

### ISSUE THREAD

**Issue by artjomb** [avibrazil/iOSbackup#4]
I've freshly installed Python 3.9.0 on my Windows 8.1 machine. There were no issues installing the two dependencies through pip and the library itself, but I have no idea how the library is to be used, because everything I do leads to an error.

I have a non-standard backup location.

1. Running as per docs

```python
>>> from iOSbackup import iOSbackup
>>> iOSbackup.getDeviceList()
Exception ignored in: <function iOSbackup.__del__ at 0x035C8148>
Traceback (most recent call last):
  File "C:\Python39-32\lib\site-packages\iOSbackup\__init__.py", line 120, in __del__
    os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39-32\lib\site-packages\iOSbackup\__init__.py", line 328, in getDeviceList
    (_, dirnames, _)=next(os.walk(root))
StopIteration
```

No idea what the issue is. Ok, maybe I need to set the root correctly and luckily there is a method for that.

2. Setting the root

```python
>>> iOSbackup.setBackupRoot('C:\\my\\path\\to\\backup')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39-32\lib\site-packages\iOSbackup\__init__.py", line 240, in setBackupRoot
    self.backupRoot=iOSbackup.getHintedBackupRoot()
AttributeError: 'str' object has no attribute 'backupRoot'
```

It seems that `iOSbackup` was not initialized, because `self` is the path that was passed in.

3. Initializing iOSbackup

```python
>>> ib = iOSbackup('myudid', backuproot='C:\\my\\path\\to\\backup')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39-32\lib\site-packages\iOSbackup\__init__.py", line 161, in __init__
    self.unlockKeys()
  File "C:\Python39-32\lib\site-packages\iOSbackup\__init__.py", line 757, in unlockKeys
    k = iOSbackup.AESUnwrap(self.decryptionKey,classkey[b"WPKY"])
  File "C:\Python39-32\lib\site-packages\iOSbackup\__init__.py", line 803, in AESUnwrap
    B = AES.new(key, AES.MODE_ECB).decrypt(todec)
  File "C:\Python39-32\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Python39-32\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Python39-32\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 215,in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Python39-32\lib\site-packages\Crypto\Cipher\AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()
```

This seems promising because some was likely found, but I've no idea how to move forward.

I would appreciate some assistance. Thank you!

**Comment by artjomb** [comment]
Never mind. I haven't set the password at this stage. What works is this:

```python
>>> from iOSbackup import iOSbackup
>>> iOSbackup.getDeviceList('C:\\my\\path\\to\\backup')
>>> ib = iOSbackup('myudid', cleartextpassword='mypassword', backuproot='C:\\my\\path\\to\\backup')
```

**Comment by agape-apps** [comment]
@artjomb could you please look at the issue below on your own Github site? (unrelated to the above issue)

https://github.com/artjomb/cryptojs-extension/issues/2
